// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/demo.proto

package api

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SendSmsReq) Validate() error {
	return nil
}
func (this *SendSmsRes) Validate() error {
	return nil
}
