// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: src/base/book/api/book.proto

package api

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_FindByIdReq_Id = regexp.MustCompile(`^[0-9a-f]{24}$`)

func (this *FindByIdReq) Validate() error {
	if !_regex_FindByIdReq_Id.MatchString(this.Id) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`ID must a bson id`))
	}
	return nil
}
func (this *BookResp) Validate() error {
	if this.Book != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Book); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Book", err)
		}
	}
	return nil
}

var _regex_Book_Id = regexp.MustCompile(`^[0-9a-f]{24}`)

func (this *Book) Validate() error {
	if !_regex_Book_Id.MatchString(this.Id) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must be a string conforming to regex "^[0-9a-f]{24}"`, this.Id))
	}
	return nil
}
