// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: src/base/user/api/user.proto

package api

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Empty) Validate() error {
	return nil
}
func (this *TokenReq) Validate() error {
	return nil
}
func (this *TokenRes) Validate() error {
	return nil
}

var _regex_InfoReq_Id = regexp.MustCompile(`^[0-9a-f]{24}$`)

func (this *InfoReq) Validate() error {
	if !_regex_InfoReq_Id.MatchString(this.Id) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`ID must a bson id`))
	}
	return nil
}
func (this *UserInfo) Validate() error {
	return nil
}
